# Generated by Django 4.2.5 on 2023-09-18 22:35

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BeneficiaryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=8)),
                ('father_name', models.CharField(max_length=64)),
                ('address', models.CharField(max_length=128)),
                ('pincode', models.IntegerField()),
                ('identity_proof', models.ImageField(upload_to='')),
                ('type_beneficiary', models.CharField(max_length=16)),
                ('mobile', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
            ],
        ),
    ]
