# Generated by Django 4.2.5 on 2023-09-18 22:57

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('ddApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiarymodel',
            name='mobile',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='IN'),
        ),
    ]
