# Generated by Django 4.2.5 on 2023-09-18 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddApp', '0003_setupinstallermodel_alter_beneficiarymodel_pincode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beneficiarymodel',
            name='id',
        ),
        migrations.RemoveField(
            model_name='setupinstallermodel',
            name='id',
        ),
        migrations.AddField(
            model_name='beneficiarymodel',
            name='unique_key',
            field=models.AutoField(default=101, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='setupinstallermodel',
            name='unique_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
