# Generated by Django 4.2.5 on 2023-09-18 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddApp', '0004_remove_beneficiarymodel_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiarymodel',
            name='unique_key',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='setupinstallermodel',
            name='unique_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
