# Generated by Django 4.2.5 on 2023-09-19 01:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ddApp', '0006_rename_unique_key_beneficiarymodel_unique_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='setupinstallermodel',
            name='installer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
