# Generated by Django 4.2.5 on 2023-09-19 02:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddApp', '0007_setupinstallermodel_installer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setupinstallermodel',
            name='name',
        ),
        migrations.AlterField(
            model_name='setupinstallermodel',
            name='address',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='setupinstallermodel',
            name='identity_proof',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='setupinstallermodel',
            name='pincode',
            field=models.CharField(max_length=6, null=True, validators=[django.core.validators.RegexValidator('^\\d{6}$', 'Enter a valid 6-digit PIN code.')]),
        ),
    ]
