# Generated by Django 4.2.5 on 2023-09-19 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ddApp', '0008_remove_setupinstallermodel_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SetupInstallerModel',
        ),
    ]
