# Generated by Django 4.2.5 on 2023-09-19 16:48

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ddApp', '0009_delete_setupinstallermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstallerModel',
            fields=[
                ('unique_id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=128, null=True)),
                ('pincode', models.CharField(max_length=6, null=True, validators=[django.core.validators.RegexValidator('^\\d{6}$', 'Enter a valid 6-digit PIN code.')])),
                ('identity_proof', models.ImageField(null=True, upload_to='')),
                ('mobile', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='IN')),
                ('installer', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
