# Generated by Django 4.2.5 on 2023-09-19 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddApp', '0010_installermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiarymodel',
            name='identity_proof',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='installermodel',
            name='identity_proof',
            field=models.CharField(max_length=32),
        ),
    ]
