# Generated by Django 4.2.5 on 2023-09-19 20:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ddApp', '0012_alter_beneficiarymodel_identity_proof_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskAssigned',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completion', models.CharField(choices=[('Initiated', 'Initiated'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], max_length=16)),
                ('beneficiary', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ddApp.beneficiarymodel')),
                ('installer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
