# Generated by Django 4.2.5 on 2023-09-19 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddApp', '0014_alter_taskassigned_completion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiarymodel',
            name='identity_proof',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
