# Generated by Django 4.2.5 on 2023-09-19 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ddApp', '0015_alter_beneficiarymodel_identity_proof'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='installermodel',
            name='installer',
        ),
        migrations.RemoveField(
            model_name='taskassigned',
            name='beneficiary',
        ),
        migrations.RemoveField(
            model_name='taskassigned',
            name='installer',
        ),
        migrations.DeleteModel(
            name='BeneficiaryModel',
        ),
        migrations.DeleteModel(
            name='InstallerModel',
        ),
        migrations.DeleteModel(
            name='TaskAssigned',
        ),
    ]
