# Generated by Django 4.2.5 on 2023-09-20 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ddApp', '0017_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskassigned',
            name='beneficiary',
        ),
        migrations.RemoveField(
            model_name='taskassigned',
            name='installer',
        ),
        migrations.DeleteModel(
            name='BeneficiaryModel',
        ),
        migrations.DeleteModel(
            name='TaskAssigned',
        ),
    ]
