# Generated by Django 4.2.5 on 2023-09-20 13:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ddApp', '0020_remove_beneficiarymodel_unique_id_taskassigned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskassigned',
            name='beneficiary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ddApp.beneficiarymodel'),
        ),
        migrations.AlterField(
            model_name='taskassigned',
            name='installer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
