# Generated by Django 4.2.5 on 2023-09-20 16:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ddApp', '0022_alter_taskassigned_completion'),
    ]

    operations = [
        migrations.CreateModel(
            name='SetupBoxInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sr_no', models.CharField(max_length=64)),
                ('passcode', models.CharField(max_length=6, null=True, validators=[django.core.validators.RegexValidator('^\\d{6}$', 'Enter a valid 6-digit PASSCODE code.')])),
                ('beneficiary_registered', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ddApp.beneficiarymodel')),
            ],
        ),
    ]
