# Generated by Django 4.2.5 on 2023-09-24 17:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ddApp', '0023_setupboxinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beneficiarymodel',
            name='address',
        ),
        migrations.RemoveField(
            model_name='beneficiarymodel',
            name='father_name',
        ),
        migrations.RemoveField(
            model_name='installermodel',
            name='address',
        ),
        migrations.AddField(
            model_name='beneficiarymodel',
            name='area_locality_sector',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='beneficiarymodel',
            name='district',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='beneficiarymodel',
            name='father_name_spouse_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='beneficiarymodel',
            name='house_bldg_apt',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='beneficiarymodel',
            name='landmark',
            field=models.CharField(blank=True, max_length=68, null=True),
        ),
        migrations.AddField(
            model_name='beneficiarymodel',
            name='post_office',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='beneficiarymodel',
            name='state',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='beneficiarymodel',
            name='street_road_lane',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='beneficiarymodel',
            name='village_town_city',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='installermodel',
            name='agency',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='installermodel',
            name='area_locality_sector',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='installermodel',
            name='district',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='installermodel',
            name='house_bldg_apt',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='installermodel',
            name='landmark',
            field=models.CharField(blank=True, max_length=68, null=True),
        ),
        migrations.AddField(
            model_name='installermodel',
            name='post_office',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='installermodel',
            name='state',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='installermodel',
            name='street_road_lane',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='installermodel',
            name='village_town_city',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='beneficiarymodel',
            name='name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='beneficiarymodel',
            name='type_beneficiary',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.CreateModel(
            name='Installed_Box_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_info', models.CharField(max_length=255)),
                ('device_location', models.CharField(max_length=255)),
                ('picture', models.FileField(upload_to='')),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ddApp.beneficiarymodel')),
                ('installer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
