# Generated by Django 4.2.5 on 2023-09-24 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddApp', '0024_remove_beneficiarymodel_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='installermodel',
            name='installer',
        ),
        migrations.AddField(
            model_name='installermodel',
            name='name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
