# Generated by Django 4.2.5 on 2023-09-24 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddApp', '0025_remove_installermodel_installer_installermodel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installermodel',
            name='mobile',
            field=models.IntegerField(),
        ),
    ]
