# Generated by Django 4.2.5 on 2023-09-24 19:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ddApp', '0026_alter_installermodel_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='installermodel',
            name='installer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
