# Generated by Django 4.2.5 on 2023-09-24 19:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddApp', '0027_installermodel_installer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installermodel',
            name='mobile',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='installermodel',
            name='pincode',
            field=models.CharField(blank=True, max_length=6, null=True, validators=[django.core.validators.RegexValidator('^\\d{6}$', 'Enter a valid 6-digit PIN code.')]),
        ),
    ]
