# Generated by Django 4.2.5 on 2023-09-25 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddApp', '0028_alter_installermodel_mobile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiarymodel',
            name='block',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
