# Generated by Django 4.2.5 on 2023-10-14 13:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddApp', '0032_alter_taskassigned_completion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setupboxinfo',
            name='passcode',
            field=models.CharField(blank=True, max_length=6, null=True, validators=[django.core.validators.RegexValidator('^\\d{4}$', 'Enter a valid 6-digit PASSCODE code.')]),
        ),
        migrations.AlterField(
            model_name='taskassigned',
            name='completion',
            field=models.CharField(choices=[('Assigned', 'Assigned'), ('Intrans-it', 'Intrans-it'), ('Initiated', 'Initiated'), ('Installation Done!', 'Installation Done!')], default='Assigned', max_length=64),
        ),
    ]
